### ISSUE TITLE
Notification Bomb on first launch

### ISSUE THREAD

**Issue by BitiTiger** [arborchat/sprig#2]
### The problem
When Sprig starts, all messages being received from the server will show up as notifications. This is especially noticeable when a user connects to a server for the first time.

### My proposed solution

- remember the system time when the client is launched
- if an incoming message is older than the system time, no notification is sent

**Comment by BitiTiger** [comment]
I can't assign myself to the issue, but I'm developing a solution.

**Comment by BitiTiger** [comment]
It is worth noting that this implementation was used for Muscadine in [this issue](https://github.com/arborchat/muscadine/issues/20) and implemented with [this pull request](https://github.com/arborchat/muscadine/pull/31)

**Comment by whereswaldon** [comment]
Thank you for reporting this and for submitting a PR for it! I'm going to close this issue in favor of [the existing sourcehut issue](https://todo.sr.ht/~whereswaldon/arbor-dev/113), but I appreciate you taking the time to file this!
