### ISSUE TITLE
Add a setting for disabling notifications

### ISSUE THREAD

**Issue by BitiTiger** [arborchat/sprig#3]
I would like to propose a new feature. The feature would be a setting for disabling all notifications. This can be implemented through a config file, a check box/switch on the server screen or on the main chat window.

**Comment by whereswaldon** [comment]
This is definitely a setting that needs to exist! I've copied this over to our [project issue tracker](https://todo.sr.ht/~whereswaldon/arbor-dev/115) and we can continue the conversation there! Thank you for submitting this!
