### ISSUE TITLE
Arabic characters not working 

### ISSUE THREAD

**Issue by m-abdalrahman** [arborchat/sprig#9]
When I run spring on Ubuntu, and start typing by Arabic words not appear

**Comment by whereswaldon** [comment]
Looks like our issue mirror was using an expired token. I updated that, and I'll update the [sourcehut issue](https://todo.sr.ht/~whereswaldon/arbor-dev/179) with details about this problem. I'm going to close this issue on GitHub, but we can keep the conversation going over on sourcehut.
